// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjvhvrwmuzesetxgmxov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqdmh2cndtdXplc2V0eGdteG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTY2MTIsImV4cCI6MjA2NTE3MjYxMn0.k6SH_CAQVt-HOfheO6XbLQFozcq2xXlD8VVONuLdAU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);